services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: tp_micro
      POSTGRES_USER: tp_user
      POSTGRES_PASSWORD: tp_pass
    ports: ["5433:5432"]
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/00_schema.sql
      - ./db/seed_bad_terms.sql:/docker-entrypoint-initdb.d/01_seed_bad_terms.sql
      - ./db/seed_texts.sql:/docker-entrypoint-initdb.d/02_seed_texts.sql

  rabbit:
    image: rabbitmq:3-management
    ports: ["5672:5672","15672:15672"]

  ingest:
    build: ./ingest-service
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: tp_micro
      POSTGRES_USER: tp_user
      POSTGRES_PASSWORD: tp_pass
      RABBIT_HOST: rabbit
    depends_on: [db, rabbit]
    ports: ["8081:8080"]

  classifier:
    build: ./classifier-service
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: tp_micro
      POSTGRES_USER: tp_user
      POSTGRES_PASSWORD: tp_pass
      RABBIT_HOST: rabbit
      RABBIT_QUEUE: incoming_texts
      RABBIT_PREFETCH: 50
    depends_on: [db, rabbit]
    ports: ["8082:8082"]

  stats:
    build: ./stats-service
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: tp_micro
      POSTGRES_USER: tp_user
      POSTGRES_PASSWORD: tp_pass
    depends_on: [db]
    ports: ["8083:8080"]

